import { useState } from 'react'
import './App.css'

const services = [
  ['01', 'Destination Weddings', 'Celebrations that feel beautifully at home, wherever you choose to say “I do.”'],
  ['02', 'Wedding Planning', 'Every meaningful detail considered, from your first idea to the last dance.'],
  ['03', 'Design & Décor', 'Thoughtful styling, florals, stage design and atmospheres made around your story.'],
  ['04', 'Food, Music & Entertainment', 'Catering, DJs, emcees, live performers and every detail that keeps the celebration moving.'],
  ['05', 'Celebrations & Events', 'Intimate milestones, grand receptions and corporate gatherings with soul.'],
]
const destinations = ['Goa', 'Mangalore', 'Udupi', 'Coorg', 'Kerala', 'Rajasthan']
const pillars = [
  ['01', 'One place', 'Venue, décor, food, photography, beauty, entertainment, transport and stay—coordinated in one place.'],
  ['02', 'Personal', 'Every celebration is shaped around your story, style and budget, never a fixed package.'],
  ['03', 'Curated', 'We bring you considered partners we trust, not an overwhelming list of random options.'],
  ['04', 'Smart', 'A clearer planning experience today, with a future dashboard and AI-assisted ideas in view.'],
  ['05', 'Seamless', 'One team brings every moving part together, so you can be present for your celebration.'],
]
const Arrow = () => <span className="arrow" aria-hidden="true">↗</span>

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const closeMenu = () => setMenuOpen(false)
  const handleSubmit = (event) => {
    event.preventDefault()
    const form = new FormData(event.currentTarget)
    const message = `Hello Anshul, I would like to plan an event with AV Eventz.\n\nName: ${form.get('name')}\nPhone: ${form.get('phone')}\nEmail: ${form.get('email')}\nEvent type: ${form.get('eventType')}\nBudget: ${form.get('budget')}\nEvent details: ${form.get('message')}`
    window.open(`https://wa.me/917204758541?text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer')
  }
  return <main>
    <header className="navbar">
      <a className="brand brand-logo" href="#home" onClick={closeMenu} aria-label="AV Eventz home"><img src="/images/av-eventz-logo-cropped.png" alt="AV Eventz — Destination Weddings, Events, Experiences" /></a>
      <button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Toggle navigation"><span></span><span></span></button>
      <nav className={menuOpen ? 'nav-links is-open' : 'nav-links'}>
        <a href="#about" onClick={closeMenu}>About</a><a href="#services" onClick={closeMenu}>Services</a><a href="#work" onClick={closeMenu}>Our Work</a><a href="#destinations" onClick={closeMenu}>Destinations</a><a href="#contact" className="nav-cta" onClick={closeMenu}>Plan your event <Arrow /></a>
      </nav>
    </header>
    <section className="hero" id="home"><div className="hero-copy"><p className="eyebrow light">Destination weddings · Thoughtful celebrations</p><h1>Plan. Personalise.<br /><em>Celebrate.</em></h1><p className="hero-text">One place to imagine, plan and enjoy an event that feels completely yours—without managing every moving part.</p><a className="button button-light" href="#contact">Begin your story <Arrow /></a></div><div className="hero-note"><span>Est. 2026</span><span>India & beyond</span></div></section>
    <section className="intro section" id="about"><p className="eyebrow">More than event planning</p><div className="intro-grid"><h2>You imagine it.<br />We bring <em>it together.</em></h2><div><p>AV Eventz is a full-service event experience studio. We pair trusted partners with thoughtful, human coordination so your entire celebration feels personal and effortless.</p><p>Technology makes planning clearer; our people make the event happen. You do not have to manage your event—you get to enjoy it.</p><a className="text-link" href="#experience">Discover our approach <Arrow /></a></div></div></section>
    <section className="image-feature section-pad"><div className="image-card image-card-large decor-feature" role="img" aria-label="Flower-filled seaside wedding ceremony decoration" ></div><div className="feature-caption"><span>(01)</span><span>Timeless details, rooted in you</span></div></section>
    <section className="services section" id="services"><div className="section-heading"><div><p className="eyebrow">What we do</p><h2>One vision.<br /><em>Every detail.</em></h2></div><p>From venues and décor to catering, DJs, emcees and guest experiences, our team plans every part with heart and precision.</p></div><div className="service-list">{services.map(([number, name, text]) => <article className="service-row" key={name}><span className="service-number">{number}</span><div><h3>{name}</h3><p>{text}</p></div><Arrow /></article>)}</div></section>
    <section className="process dark-section" id="experience"><div className="section process-head"><p className="eyebrow light">The AV Eventz experience</p><h2>A beautiful event,<br /><em>without the rush.</em></h2></div><div className="steps section">{['Tell us your vision', 'Choose what feels right', 'We bring it to life', 'You celebrate'].map((step, index) => <div className="step" key={step}><span>0{index + 1}</span><h3>{step}</h3><p>{['Share your occasion, style, destination and budget.', 'Explore thoughtfully curated ideas and services made for you.', 'Our trusted team coordinates every detail behind the scenes.', 'Be wholly there for every laugh, ritual and toast.'][index]}</p></div>)}</div></section>
    <section className="pillars section"><div className="section-heading"><div><p className="eyebrow">Our promise</p><h2>Built around <em>your experience.</em></h2></div><p>Curated partners, human care and a smarter planning journey—each part designed to make the whole event feel easy.</p></div><div className="pillar-grid">{pillars.map(([number, title, text]) => <article key={title}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <section className="portfolio section" id="work"><div className="editorial-title"><div><p className="eyebrow">A little proof</p><h2>Of what we <em>make.</em></h2></div><p>From the first flower to the final song, every layer is shaped around the people in the room.</p></div><div className="editorial-grid"><article className="editorial-card ceremony"><div><span>Christian ceremonies</span><h3>A place for promises</h3></div></article><article className="editorial-card tablescape"><div><span>Tablescapes</span><h3>Set for a feeling</h3></div></article><article className="editorial-card cuisine"><div><span>Catering</span><h3>Taste the occasion</h3></div></article><article className="editorial-card party"><div><span>Music & celebration</span><h3>Keep the night moving</h3></div></article></div></section>
    <section className="destination-showcase section" id="destinations"><div className="editorial-title"><div><p className="eyebrow">The atlas</p><h2>Where will<br /><em>we meet?</em></h2></div><p>From a quiet shore ceremony to a grand celebration, we know the country by its best-kept possibilities.</p></div><div className="destination-hero"><div><span>A country of possibilities</span><h3>The right place<br />changes <em>everything.</em></h3></div></div><div className="destination-cards">{destinations.map((destination, index) => <article className={`destination-card destination-${index}`} key={destination}><span>{String(index + 1).padStart(2, '0')} / {destination}</span><h3>{destination}</h3></article>)}</div></section>
    <section className="contact section" id="contact"><p className="eyebrow">Start a conversation</p><div className="contact-grid"><div className="contact-intro"><h2>Let’s create something <em>unforgettable.</em></h2><p>Share a few details about your celebration. Your enquiry will open directly in WhatsApp with our team.</p><div className="contact-direct"><a href="tel:+917204758541"><span>Call us</span>+91 72047 58541</a><a href="https://www.instagram.com/aveventz_?igsi=ZTNpNG80M3NtZmJp" target="_blank" rel="noreferrer"><span>Follow our work</span>@aveventz_</a></div></div><form onSubmit={handleSubmit}><div className="form-pair"><label>Your name<input required name="name" placeholder="Your name" /></label><label>Phone number<input required name="phone" type="tel" placeholder="+91" /></label></div><div className="form-pair"><label>Email address<input required type="email" name="email" placeholder="Email address" /></label><label>Event type<select required name="eventType" defaultValue=""><option value="" disabled>Select event</option><option>Wedding</option><option>Reception</option><option>Engagement</option><option>Private celebration</option><option>Corporate event</option></select></label></div><label>Estimated budget<select required name="budget" defaultValue=""><option value="" disabled>Select a range</option><option>Under ₹5 lakh</option><option>₹5–10 lakh</option><option>₹10–20 lakh</option><option>₹20 lakh+</option></select></label><label>Tell us about your event<textarea required name="message" placeholder="Date, destination, number of guests and your ideas..." rows="3"></textarea></label><button className="button button-dark" type="submit">Continue on WhatsApp <Arrow /></button><p className="form-note">No commitment—just a conversation about your celebration.</p></form></div></section>
    <a className="whatsapp" href="https://wa.me/917204758541?text=Hello%20Anshul%2C%20I%20would%20like%20to%20plan%20an%20event%20with%20AV%20Eventz." target="_blank" rel="noreferrer" aria-label="Chat with Anshul on WhatsApp"><b>◔</b><span>WhatsApp Anshul</span></a>
    <footer><div className="footer-brand"><a className="brand brand-logo" href="#home"><img src="/images/av-eventz-logo-cropped.png" alt="AV Eventz — Destination Weddings, Events, Experiences" /></a><p>Thoughtfully planned celebrations, everywhere.</p></div><div className="footer-links"><span>Connect</span><a href="https://www.instagram.com/aveventz_?igsi=ZTNpNG80M3NtZmJp" target="_blank" rel="noreferrer">Instagram</a><a href="https://wa.me/917204758541" target="_blank" rel="noreferrer">WhatsApp</a></div><div className="footer-links"><span>Contact</span><a href="tel:+917204758541">+91 72047 58541</a><a href="#contact">Plan your event</a></div><small>© 2026 AV Eventz. All rights reserved.</small></footer>
  </main>
}
export default App
