import { useEffect, useState } from 'react'
import './App.css'
import ServiceDetail from './ServiceDetail'
import serviceDetails from './serviceData'

const services = [
  ['01', 'Destination Weddings', 'From venue discovery to guest stays, we create destination weddings that feel effortless, personal and beautifully organised.', '/images/services/destination-wedding.jpg', 'Palace garden destination wedding ceremony'],
  ['02', 'Wedding Planning', 'A clear plan, trusted guidance and a dedicated team from your first conversation to your final farewell.', '/images/services/wedding-planning.jpg', 'Planning team directing a luxury Indian wedding'],
  ['03', 'Design & Décor', 'Thoughtful décor, florals and styling that reflect your story—not a one-size-fits-all celebration.', '/images/services/design-decor.jpg', 'Contemporary sculptural floral installation'],
  ['04', 'Food, Music & Entertainment', 'Memorable menus, music and entertainment chosen to delight every guest and keep the celebration alive.', '/images/services/food-music-entertainment.jpg', 'DJ-led celebration with stylish guests'],
  ['05', 'Celebrations & Events', 'Engagements, receptions, birthdays and corporate events planned with the same care as life’s biggest moments.', '/images/services/celebrations-events.jpg', 'Elegant evening party on the dance floor'],
]
const destinations = ['Goa', 'Mangalore', 'Udupi', 'Coorg', 'Kerala', 'Rajasthan']
// Each destination uses a dedicated landmark photograph, never a repeated collage.
const destinationImages = {
  Goa: ['/images/places/goa-candolim-beach.jpg'],
  Mangalore: ['/images/places/mangalore-tannirbhavi-beach.jpg'],
  Udupi: ['/images/places/udupi-krishna-temple.jpg'],
  Coorg: ['/images/places/coorg-abbey-falls.jpg'],
  Kerala: ['/images/places/kerala-backwater-houseboat.jpg'],
  Rajasthan: ['/images/places/rajasthan-city-palace.jpg'],
}
// Retained as the source set for future destination-editorial updates.
// eslint-disable-next-line no-unused-vars
const destinationGalleries = {
  Goa: ['/images/destinations/goa-1.jpg', '/images/destinations/goa-2.jpg', '/images/destinations/goa-3.jpg', '/images/destinations/goa-4.jpg', '/images/destinations/goa-5.jpg', '/images/destinations/goa-6.jpg'],
  Mangalore: ['/images/destinations/mangalore-1.jpg', '/images/destinations/mangalore-2.jpg', '/images/destinations/mangalore-3.jpg', '/images/destinations/mangalore-4.jpg', '/images/destinations/mangalore-5.jpg', '/images/destinations/mangalore-6.jpg'],
  Udupi: ['/images/destinations/udupi-1.jpg', '/images/destinations/udupi-2.jpg', '/images/destinations/udupi-3.jpg', '/images/destinations/udupi-4.jpg', '/images/destinations/udupi-5.jpg', '/images/destinations/udupi-6.jpg'],
  Coorg: ['/images/destinations/coorg-1.jpg', '/images/destinations/coorg-2.jpg', '/images/destinations/coorg-3.jpg', '/images/destinations/coorg-4.jpg', '/images/destinations/coorg-5.jpg', '/images/destinations/coorg-6.jpg'],
  Kerala: ['/images/destinations/kerala-1.jpg', '/images/destinations/kerala-2.jpg', '/images/destinations/kerala-3.jpg', '/images/destinations/kerala-4.jpg', '/images/destinations/kerala-5.jpg', '/images/destinations/kerala-6.jpg'],
  Rajasthan: ['/images/destinations/rajasthan-1.jpg', '/images/destinations/rajasthan-2.jpg', '/images/destinations/rajasthan-3.jpg', '/images/destinations/rajasthan-4.jpg', '/images/destinations/rajasthan-5.jpg', '/images/destinations/rajasthan-6.jpg'],
}
const destinationFeatureImages = {
  Goa: 'https://image.wedmegood.com/resized-nw/1300X/wp-content/uploads/2022/09/KK-09357.jpg',
  Mangalore: 'https://img.weddingbazaar.com/photos/pictures/009/137/435/new_large/unnamed-2025-12-18T124436.022.webp',
  Udupi: 'https://img.weddingbazaar.com/photos/pictures/009/193/370/new_large/1000477151.jpg',
  Coorg: 'https://media.vogue.in/wp-content/uploads/2023/03/6.jpg',
  Kerala: 'https://image.wedmegood.com/resized-nw/1300X/wp-content/uploads/2020/04/139_Aathi_Malu_281.jpg',
  Rajasthan: 'https://weddingsutra.com/images/wedding-images/desti_wed/shruti-shayaun/shruti-shayaun-img14.webp',
}
const pillars = [
  ['01', 'Everything handled', 'Venue, décor, food, photography, travel and entertainment—managed by one accountable team.'],
  ['02', 'Made for you', 'Your traditions, priorities and budget guide every recommendation we make.'],
  ['03', 'Trusted partners', 'We work with reliable, quality-focused vendors so you can choose with confidence.'],
  ['04', 'Clear planning', 'Simple communication, practical timelines and complete visibility at every stage.'],
  ['05', 'A calm celebration', 'We handle the coordination so you and your loved ones can enjoy every moment.'],
]
const Arrow = () => <span className="arrow" aria-hidden="true">↗</span>

const destinationDetails = {
  Goa: { position: 'center', season: 'November – March', capacity: '50 – 600 guests', vibe: 'Sun-kissed, effortless and celebratory', overview: 'Goa brings together golden beaches, leafy Portuguese-era villas and resorts made for long, joyful celebrations. It is ideal for couples who want their wedding weekend to feel like a holiday for every guest.', concept: 'Beach wedding', decor: 'Soft tropical florals, candlelit aisles and sunset-toned tables', venues: [['Beachfront Resort', 'Candolim', 'Beachfront resort · Indoor & outdoor', '80–450 guests'], ['Heritage Villa', 'North Goa', 'Private villa · Outdoor lawns', '40–160 guests'], ['Clifftop Celebration Space', 'South Goa', 'Boutique hotel · Indoor & outdoor', '60–250 guests']] },
  Mangalore: { position: 'center', season: 'October – February', capacity: '80 – 800 guests', vibe: 'Coastal, intimate and richly traditional', overview: 'Mangalore offers a rare balance of verdant hills, coastal air and warm local hospitality. It suits celebrations that honour tradition while still feeling intimate, relaxed and beautifully styled.', concept: 'Coastal heritage wedding', decor: 'Jasmine, brass, banana leaf details and warm ivory draping', venues: [['Hillview Resort', 'Karkala Road', 'Resort · Lawns & ballroom', '100–500 guests'], ['Coastal Garden Venue', 'Surathkal', 'Garden venue · Outdoor', '80–350 guests'], ['Boutique Banquet', 'City Centre', 'Banquet hall · Indoor', '150–800 guests']] },
  Udupi: { position: 'center', season: 'October – February', capacity: '60 – 500 guests', vibe: 'Sacred, serene and deeply rooted', overview: 'Udupi is perfect for families seeking a meaningful coastal celebration with a graceful traditional rhythm. Temple-town heritage, beaches and lush landscapes provide a quietly memorable backdrop.', concept: 'Traditional coastal wedding', decor: 'Temple-inspired florals, brass lamps and elegant coastal textures', venues: [['Seaside Resort', 'Malpe', 'Resort · Beach & lawns', '60–300 guests'], ['Heritage Courtyard', 'Udupi Town', 'Courtyard venue · Outdoor', '80–250 guests'], ['Grand Function Hall', 'Manipal', 'Convention venue · Indoor', '200–500 guests']] },
  Coorg: { position: 'center', season: 'October – March', capacity: '40 – 350 guests', vibe: 'Misty, intimate and beautifully unhurried', overview: 'Coorg is made for a close-knit celebration surrounded by coffee estates, misty hills and forested views. Its slower pace creates a naturally intimate setting for celebrations with heart.', concept: 'Nature wedding', decor: 'Wild florals, soft greens, wood accents and abundant candlelight', venues: [['Estate Retreat', 'Madikeri', 'Private estate · Lawns', '40–180 guests'], ['Hillside Resort', 'Kushalnagar', 'Resort · Indoor & outdoor', '80–350 guests'], ['Coffee Plantation Venue', 'Virajpet', 'Plantation · Outdoor', '50–200 guests']] },
  Kerala: { position: 'center', season: 'November – February', capacity: '80 – 700 guests', vibe: 'Lush, graceful and culturally rich', overview: 'Kerala brings tranquil backwaters, grand resorts and an incredible culinary tradition to your celebration. It is a beautiful choice for a refined wedding that feels rooted in place and generous in spirit.', concept: 'Kerala backwater wedding', decor: 'White jasmine, gold details, lamps and lush tropical foliage', venues: [['Backwater Resort', 'Kumarakom', 'Resort · Waterfront lawns', '80–400 guests'], ['Palace-inspired Hotel', 'Kochi', 'Luxury hotel · Indoor & outdoor', '150–700 guests'], ['Garden Retreat', 'Kovalam', 'Boutique resort · Outdoor', '60–250 guests']] },
  Rajasthan: { position: 'center', season: 'October – March', capacity: '100 – 1,000 guests', vibe: 'Royal, dramatic and unforgettable', overview: 'Rajasthan turns a wedding into a grand story. Palatial architecture, desert light and regal hospitality make it ideal for multi-day celebrations with extraordinary ceremony and spectacle.', concept: 'Royal palace wedding', decor: 'Marigolds, mirrored details, rich jewel tones and palace-scale florals', venues: [['Palace Hotel', 'Udaipur', 'Heritage hotel · Indoor & outdoor', '120–600 guests'], ['Desert Fort Venue', 'Jodhpur', 'Heritage fort · Courtyards', '100–500 guests'], ['Garden Palace', 'Jaipur', 'Luxury hotel · Lawns & ballroom', '200–1,000 guests']] },
}

// Kept for the venue-detail flow, which is currently not linked from the homepage.
// eslint-disable-next-line no-unused-vars
function VenueDetail({ venue, onBack, onClose }) {
  const [lightboxImage, setLightboxImage] = useState(null)
  const heroImage = venue.imageGallery[0]
  const enquire = () => window.open(`https://wa.me/917204758541?text=${encodeURIComponent(`Hello AV Celebrations team, I would like to enquire about ${venue.name} in ${venue.location}.`)}`, '_blank', 'noopener,noreferrer')
  return <section className="destination-modal venue-detail-page" role="dialog" aria-modal="true" aria-label={`${venue.name} venue details`}>
    <div className="destination-modal-bar"><button className="back-button" onClick={onBack}>← Back to {venue.destination} venues</button><button className="modal-close" onClick={onClose} aria-label="Close venue details">×</button></div>
    <div className={`venue-detail-hero${heroImage ? '' : ' venue-detail-hero-unverified'}`} style={heroImage ? { backgroundImage: `linear-gradient(90deg, rgba(25,20,16,.78), rgba(25,20,16,.16)), url('${heroImage}')` } : undefined}><div><p className="eyebrow light">{venue.type}</p><h1>{venue.name}</h1><p>{venue.location}</p><button className="button button-light" onClick={enquire}>Enquire now <Arrow /></button></div></div>
    <section className="venue-overview section"><div><p className="eyebrow">The venue</p><h2>A setting with<br /><em>its own story.</em></h2></div><div><p>{venue.description}</p><p>Our team confirms the final event flow, availability, pricing and on-property arrangements directly with the venue before a booking is made.</p></div></section>
    <section className="venue-facts section"><article><span>Location</span><strong>{venue.location}</strong></article><article><span>Guest capacity</span><strong>{venue.capacity}</strong></article><article><span>Pricing</span><strong>{venue.pricing}</strong></article></section>
    <section className="venue-details section"><div><p className="eyebrow">Venue details</p><h2>Planned around<br /><em>your celebration.</em></h2></div><div className="venue-detail-grid"><article><h3>Suitable celebrations</h3><p>{venue.suitableEvents.join(' · ')}</p></article><article><h3>Amenities</h3><ul>{venue.amenities.map(item => <li key={item}>{item}</li>)}</ul></article><article><h3>Spaces & stay</h3><p>Indoor and outdoor spaces, accommodation and catering are confirmed directly with the property for your selected date and celebration plan.</p></article><article><h3>Official source</h3>{venue.officialSource ? <a href={venue.officialSource} target="_blank" rel="noreferrer">Visit the property website <Arrow /></a> : <p>Official property source is being verified before publishing venue imagery.</p>}</article></div></section>
    <section className="venue-gallery-section section"><div className="detail-heading"><div><p className="eyebrow">Property gallery</p><h2>See the venue<br /><em>as it is.</em></h2></div><p>Only official or specifically approved photographs of this named property are shown here.</p></div>{venue.imageGallery.length ? <div className="venue-gallery">{venue.imageGallery.map((image, index) => <button key={image} onClick={() => setLightboxImage(image)} style={{ backgroundImage: `url('${image}')` }} aria-label={`View ${venue.name} photograph ${index + 1}`}></button>)}</div> : <div className="gallery-verification-note"><p>Official property photographs are being verified for this venue.</p><span>No generic or substitute imagery is used.</span></div>}</section>
    <section className="venue-final-cta"><div className="section"><p className="eyebrow light">Plan your celebration</p><h2>Bring your<br /><em>celebration to life.</em></h2><button className="button button-light" onClick={enquire}>Enquire now <Arrow /></button></div></section>
    {lightboxImage && <div className="image-lightbox" role="dialog" aria-modal="true" onClick={() => setLightboxImage(null)}><button aria-label="Close image">×</button><img src={lightboxImage} alt={venue.name} onClick={event => event.stopPropagation()} /></div>}
  </section>
}

function DestinationModal({ name, onClose }) {
  const destination = destinationDetails[name]
  const images = destinationImages[name]
  const featureImage = destinationFeatureImages[name]
  const [lightboxImage, setLightboxImage] = useState(null)
  const enquire = (subject) => window.open(`https://wa.me/917204758541?text=${encodeURIComponent(`Hello AV Celebrations team, I would like to plan a ${subject} in ${name}.`)}`, '_blank', 'noopener,noreferrer')
  return <section className="destination-modal" role="dialog" aria-modal="true" aria-label={`${name} destination celebrations`}>
    <div className="destination-modal-bar"><button className="back-button" onClick={onClose}>← Back to destinations</button><button className="modal-close" onClick={onClose} aria-label="Close destination details">×</button></div>
    <div className="destination-detail-hero" style={{ backgroundImage: `linear-gradient(90deg, rgba(25,20,16,.72), rgba(25,20,16,.08)), url('${images[0]}')`, backgroundPosition: destination.position }}><div><p className="eyebrow light">Destination celebrations</p><h1>{name}.<br /><em>{destination.vibe}</em></h1><p>{destination.overview}</p><button className="button button-light" onClick={() => enquire('celebration')}>Plan your {name} event <Arrow /></button></div></div>
    <div className="destination-detail section"><div className="destination-intro"><div><p className="eyebrow">The experience</p><h2>Made for moments<br />that feel <em>entirely yours.</em></h2></div><p>{name} is a natural setting for destination weddings, engagements, haldi, mehendi, sangeet, receptions, anniversaries, birthdays and polished corporate or social gatherings. Our team shapes every moment around your guests, traditions and style.</p></div><div className="destination-facts"><div><span>Best season</span><strong>{destination.season}</strong></div><div><span>Guest capacity</span><strong>{destination.capacity}</strong></div><div><span>The mood</span><strong>{destination.vibe}</strong></div></div></div>
    <div className="destination-events section"><p className="eyebrow">Weddings & celebrations</p><div className="event-chip-list">{['Destination wedding', 'Engagement', 'Haldi', 'Mehendi', 'Sangeet', 'Reception', 'Birthday celebration', 'Anniversary', 'Corporate & social event'].map(event => <span key={event}>{event}</span>)}</div></div>
    <section className="destination-gallery-section section"><div className="destination-feature-layout"><div><p className="eyebrow">The AV Celebrations edit</p><h2>What we can create<br /><em>in {name}.</em></h2><p>A considered mix of local scenery, celebration details, décor, food and atmosphere—shaped into one experience by AV Celebrations.</p></div><button type="button" className="destination-feature-image" onClick={() => setLightboxImage(featureImage)} aria-label={`View ${name} celebration inspiration`}><img src={featureImage} alt={`${name} celebration and décor inspiration`} /></button></div></section>
    <div className="inspiration-section"><div className="section inspiration-grid"><div><p className="eyebrow light">Event inspiration</p><h2>{destination.concept}<br /><em>with your signature.</em></h2></div><div><span>Suggested décor</span><p>{destination.decor}</p><span>Recommended functions</span><p>Welcome evening, mehendi, haldi, ceremony, reception and farewell brunch.</p><span>Ideal guest count</span><p>{destination.capacity}</p><button className="button button-light" onClick={() => enquire(destination.concept)}>Create this experience <Arrow /></button></div></div></div>
    <div className="destination-detail section event-inclusions"><p className="eyebrow">Complete event planning</p><div>{[['Stay & hospitality', 'Accommodation, guest welcomes, rooming and thoughtful on-ground care.'], ['Food & experiences', 'Curated menus, live counters, bars, music and entertainment.'], ['Design & coordination', 'Décor, photography, transport, timelines and a dedicated event team.'], ['Your investment', 'A tailored budget based on guest count and choices—shared transparently after consultation.']].map(([title, copy]) => <article key={title}><h3>{title}</h3><p>{copy}</p></article>)}</div><button className="button button-dark" onClick={() => enquire('destination celebration')}>Start planning in {name} <Arrow /></button></div>
    {lightboxImage && <div className="image-lightbox" role="dialog" aria-modal="true" onClick={() => setLightboxImage(null)}><button aria-label="Close image">×</button><img src={lightboxImage} alt={`${name} celebration inspiration`} onClick={event => event.stopPropagation()} /></div>}
  </section>
}

function App() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [selectedDestination, setSelectedDestination] = useState(null)
  const [enquiryReady, setEnquiryReady] = useState(false)
  const [serviceRoute, setServiceRoute] = useState(() => window.location.pathname.replace(/^\//, ''))
  useEffect(() => {
    const handlePopState = () => setServiceRoute(window.location.pathname.replace(/^\//, ''))
    window.addEventListener('popstate', handlePopState)
    return () => window.removeEventListener('popstate', handlePopState)
  }, [])
  const closeMenu = () => setMenuOpen(false)
  const openService = (slug) => {
    window.history.pushState({}, '', `/${slug}`)
    setServiceRoute(slug)
    window.scrollTo(0, 0)
  }
  const backToServices = () => {
    window.history.pushState({}, '', '/#services')
    setServiceRoute('')
    window.setTimeout(() => document.querySelector('#services')?.scrollIntoView(), 0)
  }
  const handleSubmit = (event) => {
    event.preventDefault()
    const form = new FormData(event.currentTarget)
    const message = `Hello AV Celebrations team, I would like help planning an event.\n\nName: ${form.get('name')}\nPhone: ${form.get('phone')}\nEmail: ${form.get('email')}\nDestination: ${form.get('destination')}\nEvent type: ${form.get('eventType')}\nGuest count: ${form.get('guestCount')}\nEvent date: ${form.get('eventDate')}\nBudget: ${form.get('budget')}\nEvent details: ${form.get('message')}`
    window.open(`https://wa.me/917204758541?text=${encodeURIComponent(message)}`, '_blank', 'noopener,noreferrer')
    setEnquiryReady(true)
    event.currentTarget.reset()
  }
  if (serviceDetails[serviceRoute]) return <ServiceDetail slug={serviceRoute} onBack={backToServices} />
  return <main>
    <header className="navbar">
      <a className="brand brand-logo" href="#home" onClick={closeMenu} aria-label="AV Celebrations home"><img src="/images/av-celebrations-logo-new.png" alt="AV Celebrations — Moments That Matter" /></a>
      <button className="menu-button" onClick={() => setMenuOpen(!menuOpen)} aria-expanded={menuOpen} aria-label="Toggle navigation"><span></span><span></span></button>
      <nav className={menuOpen ? 'nav-links is-open' : 'nav-links'}>
        <a href="#home" onClick={closeMenu}>Home</a><a href="#about" onClick={closeMenu}>About</a><a href="#services" onClick={closeMenu}>Services</a><a href="#destinations" onClick={closeMenu}>Destinations</a><a href="#work" onClick={closeMenu}>Our work</a><a href="#experience" onClick={closeMenu}>How we work</a><a href="#contact" className="nav-cta" onClick={closeMenu}>Plan your celebration <Arrow /></a>
      </nav>
    </header>
    <section className="hero" id="home"><div className="hero-copy"><p className="eyebrow light">Destination weddings · Celebrations · India & beyond</p><h1>You dream it.<br /><em>We make it happen.</em></h1><p className="hero-text">Premium destination weddings and celebrations, thoughtfully planned around your people, place and story.</p><a className="button button-light" href="#contact">Start planning <Arrow /></a></div><div className="hero-note"><span>AV Celebrations</span><span>Made personal</span></div></section>
    <section className="intro-editorial intro-reference section" id="about" aria-label="AV Celebrations introduction"><div className="intro-copy"><p className="eyebrow">A celebration you can enjoy</p><h2>Made for moments<br />that feel <em>entirely yours.</em></h2><p>AV Celebrations brings destination planning, guest hospitality, design and décor, vendor coordination, food, entertainment, logistics and on-ground execution into one considered celebration experience.</p><p>We listen first, then bring together the people, ideas and details that let you stay present for what matters most.</p><a className="button button-terra" href="#experience">How we make it easy <Arrow /></a></div><div className="intro-collage"><figure className="collage-main"><img src="/images/seaside-decoration-banner.png" alt="Elegant destination wedding ceremony with floral décor at sunset" /></figure><div className="collage-stamp"><span>AV Celebrations</span><b>AV</b><span>Moments that matter</span></div></div></section>
    <section className="services section" id="services"><div className="section-heading"><div><p className="eyebrow">How we help</p><h2>One team.<br /><em>Every detail.</em></h2></div><p>Whether you need complete planning or help with selected services, we make every decision simpler and every moment more memorable.</p></div><div className="service-list">{services.map(([number, name, text, image, alt]) => { const slug = Object.entries(serviceDetails).find(([, service]) => service.title === name)?.[0]; return <button type="button" className="service-row" key={name} onClick={() => openService(slug)} aria-label={`Explore ${name}`}><span className="service-number">{number}</span><div className="service-copy"><h3>{name}</h3><p>{text}</p></div><img className="service-image" src={image} alt={alt} /><Arrow /></button> })}</div><a className="services-link" href="#contact">Let’s plan yours <Arrow /></a></section>
    <section className="process dark-section" id="experience"><div className="section process-head"><p className="eyebrow light">The AV Celebrations experience</p><h2>A beautiful event,<br /><em>without the rush.</em></h2></div><div className="steps section">{['Tell us your vision', 'Choose what feels right', 'We bring it to life', 'You celebrate'].map((step, index) => <div className="step" key={step}><span>0{index + 1}</span><h3>{step}</h3><p>{['Share your occasion, style, destination and budget.', 'Explore thoughtfully curated ideas and services made for you.', 'Our trusted team coordinates every detail behind the scenes.', 'Be wholly there for every laugh, ritual and toast.'][index]}</p></div>)}</div></section>
    <section className="pillars section"><div className="section-heading"><div><p className="eyebrow">Our promise</p><h2>Built around <em>your experience.</em></h2></div><p>Curated partners, human care and a smarter planning journey—each part designed to make the whole event feel easy.</p></div><div className="pillar-grid">{pillars.map(([number, title, text]) => <article key={title}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></section>
    <span id="work" className="section-anchor" aria-hidden="true"></span><section className="destination-showcase section" id="destinations"><div className="editorial-title"><div><p className="eyebrow">The atlas</p><h2>Where will<br /><em>we meet?</em></h2></div><p>From sun-kissed shores to royal palaces, explore the extraordinary destinations where your story can unfold.</p></div><div className="destination-hero"><div><span>A country of possibilities</span><h3>The right place<br />changes <em>everything.</em></h3></div></div><div className="destination-cards">{destinations.map((destination, index) => <button type="button" className={`destination-card destination-${index}`} key={destination} onClick={() => setSelectedDestination(destination)} aria-label={`Explore ${destination}`}><span>{String(index + 1).padStart(2, '0')} / {destination}</span><h3>{destination}</h3><b>Explore destination <Arrow /></b></button>)}</div></section>
    <section className="contact section" id="contact"><p className="eyebrow">Plan your celebration</p><div className="contact-grid"><div className="contact-intro"><h2>Let’s create something <em>worth remembering.</em></h2><p>Tell us a little about your occasion. Your enquiry message opens directly in WhatsApp for you to send to our planning team.</p><div className="contact-direct"><a href="tel:+917204758541"><span>Call us</span>+91 72047 58541</a><a href="https://www.instagram.com/avcelebrations.in?utm_source=qr&stkn=Mm43emMyNnhzbjR4" target="_blank" rel="noreferrer"><span>Follow our work</span>@avcelebrations.in</a></div></div><form onSubmit={handleSubmit}><div className="form-pair"><label>Your name<input required name="name" placeholder="Your name" /></label><label>Phone number<input required name="phone" type="tel" pattern="[0-9+() -]{7,}" placeholder="+91" /></label></div><div className="form-pair"><label>Email address<input required type="email" name="email" placeholder="Email address" /></label><label>Destination<select required name="destination" defaultValue=""><option value="" disabled>Select destination</option>{destinations.map(destination => <option key={destination}>{destination}</option>)}<option>Not decided yet</option></select></label></div><div className="form-pair"><label>Event type<select required name="eventType" defaultValue=""><option value="" disabled>Select event</option><option>Wedding</option><option>Reception</option><option>Engagement</option><option>Private celebration</option><option>Corporate event</option></select></label><label>Approximate guest count<input required name="guestCount" type="number" min="1" placeholder="e.g. 200" /></label></div><div className="form-pair"><label>Event date<input required name="eventDate" type="date" /></label><label>Estimated budget<select required name="budget" defaultValue=""><option value="" disabled>Select a range</option><option>Under ₹5 lakh</option><option>₹5–10 lakh</option><option>₹10–20 lakh</option><option>₹20 lakh+</option></select></label></div><label>Tell us about your event<textarea required name="message" placeholder="Your ideas, priorities and anything else we should know..." rows="3"></textarea></label><button className="button button-dark" type="submit">Start the conversation <Arrow /></button>{enquiryReady && <p className="form-confirmation" role="status">Thank you. Your enquiry message is ready in WhatsApp—please press Send to share it with our team.</p>}<p className="form-note">No commitment—just a thoughtful first conversation.</p></form></div></section>
    <a className="whatsapp" href="https://wa.me/917204758541?text=Hello%20AV%20Celebrations%20team%2C%20I%20would%20like%20help%20planning%20an%20event." target="_blank" rel="noreferrer" aria-label="Chat with AV Celebrations on WhatsApp"><b>◔</b><span>Chat with AV Celebrations</span></a>
    <footer className="site-footer"><div className="footer-inner"><div className="footer-brand"><a className="brand brand-logo" href="#home" aria-label="AV Celebrations home"><img src="/images/av-celebrations-logo-new.png" alt="AV Celebrations — Moments That Matter" /></a><p>Thoughtful celebrations,<br />beautifully brought to <em>life.</em></p></div><nav className="footer-links footer-explore" aria-label="Footer navigation"><span>Explore</span><a href="#services">Services</a><a href="#destinations">Destinations</a><a href="#work">Gallery</a><a href="#experience">How we work</a><a href="#contact">Contact us</a></nav><div className="footer-links footer-connect"><span>Connect</span><a href="https://www.instagram.com/avcelebrations.in?utm_source=qr&stkn=Mm43emMyNnhzbjR4" target="_blank" rel="noreferrer"><b>◎</b>Instagram</a><a href="https://wa.me/917204758541" target="_blank" rel="noreferrer"><b>◔</b>WhatsApp</a></div><div className="footer-links footer-contact"><span>Contact</span><a href="tel:+917204758541"><b>⌕</b>+91 72047 58541</a><a href="mailto:avcelebrationsin@gmail.com"><b>✉</b>avcelebrationsin@gmail.com</a><p><b>⌖</b>India</p></div><div className="footer-signature"><span>India · Destination · Celebrations</span><i></i></div></div><div className="footer-bottom"><small>© 2026 AV Celebrations. All rights reserved.</small><div><a href="#home">Privacy policy</a><a href="#home">Terms</a><a href="#home">Sitemap</a></div></div></footer>
    {selectedDestination && <DestinationModal name={selectedDestination} onClose={() => setSelectedDestination(null)} />}
  </main>
}
export default App
